use ai_lavanya;
show databases;
create table product_details (Product_Id int not null primary key, Product_name varchar(50), Price int, Quantity int);
show tables;
insert into product_details (Product_Id,Product_name,Price,Quantity) values (1,'Mamaearth',200,50),(2,'Saree',199,25),(3,'Goodvibes',198,30),(4,'Turmeric Powder',75,20);  
show tables;
select * from product_details;
select Product_name from product_details;
select * from product_details order by Price ASC;
select * from product_details order by Quantity DESC;
select * from product_details order by Product_name ASC;
insert into product_details values (5,'Himalaya',200,65);
describe product_details;
select * from product_details where Price > 100;
select * from product_details where Quantity < 50;
select * from product_details where Product_name like 'M%' or price > 100;
select * from product_details where product_name not like 'G%';
alter table product_details add column Ex_date date;
update product_details set Ex_date = '2024-03-06' where product_name = 'Himalaya';
insert into product_details values (6,'Ponds',150,18,'2025-05-12');
delete from product_details where Product_name = 'Mamaearth';
insert into product_details values (1,'Mamaearth',200,50,'2025-11-09');
select * from product_details where not Price > 150;
select * from product_details where Price = 200 limit 2;
select min(Quantity) from product_details;
select max(Price) from product_details;
select count(Quantity) from product_details where Quantity < 50;
select * from product_details where Quantity not in (50);
select * from product_details where Ex_date between '2024-01-01' and '2024-07-01';